// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

//gate:kind reachability H2

package gates

// The write-shape obligation as a fitness function: every mutation that
// writes an audit row commits a paired outbox event on the same static call path
// (data-model §11, events.md §4.2 — spelled once in storekit), across
// modules AND the composition layer. A mutation that audits without
// emitting silently exempts itself from the event backbone; this test
// turns that from a reviewer memory into a gate. Exceptions are explicit,
// keyed by package path + function so a same-named function elsewhere is
// never silently waived, and each carries the decision that ratified it —
// an allow-list entry without a reason is a finding, not a pass. A waiver
// that no longer matches an audit-only function is stale and fails too.

import (
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/margince/margince/backend/internal/shared/gatekit"
)

// auditOnlyWrites are the ratified audit-without-event functions, keyed
// by "package-dir:FuncName". Every entry carries the rationale for the
// waiver inline, so the gate is self-contained on a clean checkout; an
// entry without a rationale is a finding, not a pass. When the spec's
// events.md gains the missing event types, wiring storekit.Emit into
// these mutations removes the entries.
var auditOnlyWrites = gatekit.Waive(map[string]string{
	"internal/modules/people:refuseLinkedInMatchInTx": "a suggestion the member refused, recorded on the connection so the sweep stops re-matching a question already answered. There is no event because the CONTRACT says there is none to publish: linkedin_match.decided carries no verdict, and its own description gives the reason — a refusal is an approval row that stays rejected and never becomes a link, so there is no \"no\" to publish. Emitting the decided event here would announce a link that was not made, to subscribers whose only use for it is that one was. Nothing downstream is left stale either: what a subscriber acts on is the LINK, and the accept path ships it. The audit row answers what the connection cannot once it reads `rejected` — which decision put it there, and what it was before — and it is written only on the transition, so neither of its two callers — the reject effect and the sweep's repair pass — records anything twice",
	"internal/modules/deals:RestorePipeline":          "a retired pipeline put back in use. There is no event because the CONTRACT defines none: the catalog carries pipeline.archived and no pipeline.restored, and the closed-verb law forbids inventing one build-side. Nothing downstream is left stale either — what a subscriber acts on is which pipelines are available, and every reader of that asks listPipelines, which answers from the column this write clears. The audit row is what the row itself cannot say once archived_at reads NULL: that it HAD been retired, when, and who put it back. Its sibling ArchivePipeline does emit, because the catalog has a type for that half",
	"internal/modules/consent:recordBasis":            "the lawful ground an outbound message was permitted on. The closed catalog (events.md \u00a75) defines no communication_basis.* type and the closed-verb law forbids inventing one build-side — and a verb here would be the wrong thing to want: the row is a legal CONCLUSION about a named person, and publishing it would put that conclusion in front of every subscriber, including ones with no business reading why we may write to somebody. Nothing downstream is left stale either, because nothing downstream acts on a basis: the engine re-derives it from the evidence on every decision, and the readers are the subject-access export and the erasure sweep, both of which read the table directly. The audit row is what answers \"who caused this ground to be recorded, and when\" — the question a subject asking why we wrote to them raises, and the one the row itself cannot answer. Its sibling RecordQualifyingEvent is audit-only on the same ground",
	"internal/modules/consent:OpenNoticeCaseTx":       "the disclosure this workspace owes a contact it obtained without asking them. The closed catalog (events.md \u00a75) defines no privacy_notice_case.* type and the closed-verb law forbids inventing one build-side — and a verb here would be the wrong thing to want: the row says a NAMED person has not yet been told we hold their data, and publishing that would put an unmet legal obligation about an individual in front of every subscriber. Nothing downstream is left stale either, because nothing downstream acts on a case being opened: the only readers are the privacy queue, which reads the table directly ordered by deadline, and the subject-access export. The audit row answers \"when did this workspace learn it owed this person a disclosure, and what opened the case\" — the question an auditor asks of a compliance record, and the one the row itself cannot answer once somebody has closed it",
	"internal/modules/consent:dischargeNoticeCases":   "the OTHER half of the same row, and audit-only for the same reason its opener is: the closed catalog (events.md \u00a75) defines no privacy_notice_case.* type, and a verb here would publish that a NAMED person has now been told we hold their data — an individual's compliance state in front of every subscriber. Nothing downstream is left stale either: the only readers that ACT on a case's state are the privacy queue, which reads the table directly ordered by deadline, and the subject-access export — the two erasure paths (privacy/erasure.go, privacy/retentionactions.go) delete the row by person and never read what it held. The audit row answers \"when was this duty discharged, by which route, and what did the case hold before\" — the question an auditor asks of a closed obligation, and the one the row cannot answer once a later send has moved it again. It carries BOTH images, which the opener does not need to and this does: a discharge is only legible against the state it moved from",
	"internal/modules/consent:PublishTextVersionTx":   "the installation's own wording, published once. The closed catalog (events.md \u00a75) defines no consent_text_version.* type and the closed-verb law forbids inventing one build-side — and there is nothing for a subscriber to act on: publishing wording changes no record, and the only reader is a proof row resolving the version it names, which reads the table directly. Nothing downstream is left stale either, because the row is immutable once written: a consumer that missed the event would find the same text whenever it looked. The audit row answers \"who published this wording, and under which hash\" — the question a dispute about what a subject was shown raises, and the one the row itself cannot answer because it records the text and not the act",
	"internal/compose/org360:recordEvidence":          "the words each buying role was read from. The MUTATIONS in this transaction are the seats themselves, and every one of them already ships relationship.created through the module's own writer — announcing this row too would report one reading as two. It is not a record fact at all: it is evidence ABOUT the writes beside it, landing on an audit row because the relationship table carries no evidence column and adding one for this is a schema change the committee card does not need. Nothing downstream is left stale either, because nothing downstream is waiting on it — the seats are what a subscriber acts on, and they emitted. The audit row answers \"what did the product read to seat this person\", which is recordable nowhere else once the response is gone, and which a reviewer disputing an agent-written role has to be able to open",
	"internal/modules/capture:ShareHistory":           "a seat re-opening the mail their own counterparty hold caught. The closed catalog (events.md \u00a75) defines no capture_import.* type and the closed-verb law forbids inventing one build-side. What subscribers actually need IS emitted, per message, by the recompute this same transaction runs: re-opening an import changes what the message's contributors ask for, and activities.RecomputeAudienceTx ships activity.updated carrying the new audience for every row that moved. A second event announcing the batch would report one act twice, and one announcing a pass that moved nothing would tell every subscriber that mail changed when none did. The audit row answers what no activity.updated does — that ONE seat asked for this, and how many of their messages it reached — which is the question a later dispute about who published a lawyer's correspondence asks",
	"internal/modules/capture:AskWhoseRecord":         "the sweep opening a question the ceiling refused at capture, about a contact that would otherwise stay the mailbox owner's for good. The closed catalog (events.md \u00a75) defines no type for a question being RAISED, and the closed-verb law forbids inventing one build-side. Nothing downstream is waiting on it either: what subscribers act on is the ANSWER, and when one arrives the verdict path ships person.updated through the module's own writer as it promotes the record. The audit row answers what no later event does — that this contact was put back in front of a model on a given day, and on what address — which is the question somebody asking why a private contact became visible to the workspace has to be able to open",
	"internal/compose:carryOut":                       "the RELEASE arm of a purge, dropping one seat's claim on a message a colleague also imported. Both purge paths run it — an owner acting on their own exclusion rule, and the sweep that destroys personal mail once its window closes — so this one waiver covers what used to be Purge alone. The closed catalog (events.md §5) defines no activity.import_released type and the closed-verb law forbids inventing one build-side. What subscribers actually need IS emitted, by the recompute in this same transaction: releasing an importer changes what the message's remaining contributors ask for, and activities.RecomputeAudienceTx ships activity.updated carrying the new audience when it moves. A second event announcing the same change would report one act twice, and one announcing a release that changed no audience would tell every subscriber a message moved when it did not. The audit row answers what nothing else records — WHO stopped being able to read this message, and when — which is the question a later access dispute asks",
	"internal/modules/people:RequestVatCheck":         "a person asking for the EU register to be consulted again. Nothing about the company has changed — the question has been asked and not yet answered — so there is no fact to announce, and organization.updated would tell every subscriber a company's VAT standing moved when it has not. The ANSWER emits: RecordVatCheck ships organization.updated carrying the verdict, which is the event a mirror actually needs, and emitting here would report one consultation as two. Nothing downstream is left stale either, because nothing downstream is waiting on the request — the worker that answers it is enqueued in this same transaction and carries the organization id. The audit row answers \"who spent a consultation on this company\", which is recordable nowhere else: the worker runs under a confined system principal, so the receipt it later writes names system:vatcheck whatever prompted it",
	"internal/modules/agents/runner:auditDecision":    "a rep answering whether an agent may work overnight on their behalf. The closed catalog (events.md \u00a75) defines no agent_standing_grant.* type and the closed-verb law forbids inventing one build-side; the nearest verb, passport.revoked, is about a CREDENTIAL and cannot express a decision — a rep who declines mints nothing, so there is no passport for it to name. Nothing downstream is left stale either: the only consumer is the nightly fan-out, which enumerates live grants from the row itself on its next pass, and no subscriber could act sooner than a run that has not been scheduled yet. The audit row is what answers \"who agreed to be acted for, by which agent, and what did they say before\" — the question standing authority actually raises, and it carries both images",
	"internal/modules/dealrooms:openSession":          "a buyer exchanging their invitation for a session. The closed catalog (events.md §5) defines no deal_room.session_* type and the closed-verb law forbids inventing one build-side; the nearest verb, deal_room.participant_invited, would announce an admission that already happened. Nothing downstream is left stale: the seller's roster reads has_signed_in and last_seen_at from the session rows themselves. The audit row answers \"when did this person first get in\", which a dispute about who saw what reads. Buyer engagement as a published signal is its own slice and owns the event when it lands",
	"internal/modules/dealrooms:SignOut":              "the same session ending at the buyer's own hand. Audit-only on the same ground as openSession: no deal_room.session_* verb exists, the roster reads the row, and the revocation that matters to subscribers — the seller's — already emits deal_room.participant_revoked",
	"internal/modules/approvals:signingKey":           "the Ed25519 key this installation signs approval tokens with, minted lazily on the first token. The closed catalog (events.md §5) defines no signing_key.* type and the closed-verb law forbids inventing one build-side — and a verb here would be the wrong thing to want: the subject is CRYPTOGRAPHIC MATERIAL, and announcing its arrival would put the existence and identifier of a private key in front of every subscriber, including the webhook fan-out. Nothing downstream is left stale either: a verifier resolves the kid from the row when a token presents it, which is the only moment anything needs to know the key exists, and it happens in the same transaction as the token that names it. The audit row answers what the key row cannot — who was in the building when this key came into existence — and carries the kid alone, never the material",
	"internal/modules/approvals:RedeemInTx":           "an agent spending the token a human approved. The closed catalog (events.md §5) carries exactly two approval verbs — approval.requested and approval.decided — and no approval.redeemed; the closed-verb law forbids inventing one build-side, and approval.decided would be a lie, because the decision was announced when the human made it and coming back to spend it is not a second decision. What subscribers actually act on IS emitted: the change the agent then makes ships its own event from the owning module's writer, inside the transaction this redemption opens (RedeemAndApply), so an event here would announce one act twice. Nothing downstream is left stale either — the agent's own task poll and the lapse sweep both read consumed_at from the row. The audit row answers what nothing else records: that this agent DID come back, and when — the fact whose absence the lapse mark exists to state, and which that mark can no longer distinguish once it has fired",
	"internal/modules/approvals:rebundleJoinedInTx":   "a pending proposal moving onto a fresher bundle so the human decides it with its siblings. Nothing a subscriber holds moves: approval.requested's payload is the kind, summary, target and expiry, and carries no bundle at all, so there is no stale field for an event to correct — and re-announcing it would report one proposal twice. approval.decided is worse than unavailable: the proposal is still pending, and announcing a decision nobody made would have consumers acting on a verdict that does not exist. Nothing downstream is left stale either, because the grouping is read from the row by the card that renders it. The audit row carries both bundle images, which is what answers \"which decision did this proposal end up being made under\" once the bundles have been decided and cleared",
	"internal/modules/approvals:supersedePendingInTx": "an older pending proposal retired because a fresher one for the same target arrived. The only candidate verb is approval.decided, whose verdict would have to be `expired` — and that word already means something else here, the one thing the expiry sweep says with it: the window closed with nobody deciding. Publishing it would tell every consumer a question was abandoned when in fact it was replaced, and a mirror acting on that would report the proposal as unanswered. This is the same ground WithdrawInTx beside it stands on, and the terminal status both of them write is what keeps the sweep from publishing that false verdict on their behalf. What subscribers do act on IS emitted in this same transaction: the survivor stages and ships approval.requested. The audit row carries the pending→expired transition and names the survivor, which is what answers \"what happened to the proposal I was looking at\"",
	"internal/modules/approvals:WithdrawInTx":         "the module that raised an offer taking it back — the capture ledger ageing out a question that stopped being one. Deliberately event-free, and for a reason stronger than an absent verb: the closed catalog (events.md §5) has no retraction type, and the nearest, approval.decided/expired, would tell every consumer that nobody answered a question somebody deliberately withdrew. Writing the terminal status is what stops the expiry sweep publishing exactly that a few minutes later, which is the whole design of this call. Nothing downstream is left stale: the inbox reads status from the row, and a decided approval is left alone because what a human answered is not the caller's to take back. The audit row carries the transition and the retraction's reason, which is what a rep asking where their card went reads",
	"internal/modules/activities:recordPin":           "a rep putting one row at the top of their OWN day. The closed catalog (events.md §5) defines no worklist_pin.* type and the closed-verb law forbids inventing one build-side — and a verb here would be the wrong thing to want: a pin changes the ORDER of one person's page and nothing else reads it, so a subscriber receiving it could act on nothing. Nothing downstream is left stale either, because nothing downstream consumes the order: the queue re-reads the pins on every assembly, and the only reader of that table is the page the pinner is looking at. The audit row answers \"who reordered their own day, and when\", which is recordable nowhere else once the row leaves the queue — and it is what a later question about a rep's priorities reads",

	"internal/modules/activities:startTranscriptReadInTx":      "the run record for reading a meeting transcript is operational reading STATUS, not a record fact — the closed catalog (events.md \u00a75) defines no transcript_read.* type and the closed-verb law forbids inventing one build-side. The reading is the same species as the deep-read dossier and waived on the ground that dossier's own start used to be: what the reading produces lands as staged approvals, each emitting its own event when it is accepted. (The dossier now announces itself to the AI-activity projection on that same path, which is why it is no longer listed here.) Nothing downstream could act sooner either — the only consumer is the job enqueued in this same transaction, which carries the row id. The audit row answers \"who asked for this transcript to be read\"",
	"internal/modules/activities:finishTranscriptReadTx":       "the same run record reaching a terminal state, written by the worker. Audit-only on the same ground as StartTranscriptReadQueued: no transcript_read.* verb exists in the closed catalog, and the proposals the reading staged already emitted approval.requested as they were staged — announcing the reading separately would report one act twice. The polling client reads the row itself, sooner than a subscriber could tell it. The audit row carries the outcome and how many proposals it produced, which is what a spend or quality question reads",
	"internal/modules/activities:scheduleSend":                 "a rep committing to send a message later (ADR-0104/A155). The closed catalog (events.md \u00a75) defines no scheduled_send.* type and the closed-verb law forbids inventing one build-side; activity.captured is the nearest candidate and would be a lie, because the whole point of the design is that NO activity exists until the message fires. Nothing downstream is left stale either: the only consumer is the timer, which is enqueued in this same transaction and carries the row id. The audit row is what answers \"who agreed to send this, and when did they say\" — which is the question a scheduled message raises",
	"internal/modules/activities:RescheduleInTx":               "moving a pending message to a different moment. Audit-only on the same ground as scheduleSend: no scheduled_send.* verb exists in the closed catalog, and the fresh timer this enqueues in the same transaction is the only thing that had to learn about the move. The audit row carries both moments, which is what answers \"who pushed this to Monday\"",
	"internal/modules/activities:CancelInTx":                   "a rep withdrawing a message before it fires. Audit-only on the same ground as scheduleSend: no scheduled_send.* verb exists in the closed catalog, and nothing was ever announced to retract — no activity and no delivery were written when it was scheduled. The timer needs no telling either: it wakes, reads a row that is no longer pending, and does nothing. The audit row answers \"who called it off\"",
	"internal/modules/activities:releaseInTx":                  "a scheduled message becoming a real send. The send it performs emits activity.captured in this SAME transaction (sendPreparedTx \u2192 logActivityInTx), so the fact IS announced — announcing the scheduled row separately would report one send as two. The audit row records which intention produced which activity, which is the link the timeline itself does not carry",
	"internal/modules/activities:holdInTx":                     "a scheduled message refused at fire and handed back to a human. No scheduled_send.* verb exists in the closed catalog, and no activity was written to attach one to — the message did not send, which is the entire fact. Nothing downstream can act on it either: the rep is the only actor who can resolve a hold, and they read the row. The audit row carries the reason, which is what the rep and any later investigation both need",
	"internal/modules/integrations:queueOne":                   "queueing a run is a decision to SPEND, not a fact about a record. The closed catalog (events.md \u00a75) defines no provider_run.* type and the closed-verb law forbids inventing one build-side; the platform deliberately emits nothing of its own, and the surfaces poll the run instead (PI-EVT-1 makes person.created a CONSUMED event, not a published one). Nothing downstream could act on it either: the values a subscriber would want do not exist yet — the run has not been submitted, let alone answered — and when they do arrive they are written by the owning domain as claims, which is where a consumer belongs. The audit row carries what a spend investigation reads: which subject, which provider, which trigger",
	"internal/modules/integrations:Connect":                    "binding, rotating or reconfiguring a licensed data provider is installation configuration, not a record fact. The closed catalog (events.md \u00a75) defines no provider_connection.* type and the closed-verb law forbids inventing one build-side; it is also the same family as capture_settings and the other ADR-0090 configuration surfaces, which events.md \u00a75.3c ratifies as audit-only. Nothing downstream is left stale either: a run resolves the connection at queue time and freezes what it read, so a subscriber could not act on the change any sooner than the next run already does. The audit row carries the whole fact a spend investigation reads — who connected which provider, under which policy — and deliberately carries neither the key nor a balance",
	"internal/modules/integrations:Disconnect":                 "the mirror of Connect, and audit-only for the same reason: the connection is installation configuration with no event type in the closed catalog. The cancellation it performs is visible where it matters — the cancelled runs are rows the surfaces already read — and the epoch bump it writes is what stops in-flight work, which no subscriber could do faster",
	"internal/modules/integrations:UpdateConfig":               "a policy patch on the same configuration row, audit-only on the same events.md \u00a75.3c ground as Connect. The audit image carries both sides of the change, which is what answers \"who widened what this run was allowed to spend\" — the question a surprised customer actually asks",
	"internal/modules/consent:RecordQualifyingEvent":           "a human writing down the one lawful basis nothing can derive — a card handed over at a trade fair, which happened away from every system. The closed catalog (events.md \u00a75) defines no consent_qualifying_event.* type and the closed-verb law forbids inventing one build-side; the nearest, consent.changed, would be a lie, because no consent state moved and nothing was granted. Nothing downstream is left stale either: the verdict reads the row itself on the next send, which no subscriber could do sooner. The audit row carries what an auditor asks — who said this happened, when, and in what words",
	"internal/modules/capture:SetMailPosture":                  "what one mailbox asks of its own mail is capture POSTURE, the same family as SetSignatureEnrichment below and the other configuration surfaces the closed event catalog defines no capture_connection.* type for. Nothing downstream is left stale: the sink reads mail_posture itself, inside the transaction that captures the next message, which no subscriber could do sooner — and the audience of mail ALREADY captured is deliberately not moved by this write (apply-to-history is its own call, and it emits activity.updated per row through the audience derivation). The audit row carries the before-image, the new posture and which mailbox moved, which is what \"who opened this mailbox up, and what was it before\" needs",
	"internal/modules/capture:SetContextTag":                   "which word a mailbox files what it captures under is capture POSTURE, the same family as SetMailPosture and SetSignatureEnrichment above — configuration the closed event catalog (events.md \u00a75) defines no capture_connection.* type for, and the closed-verb law forbids inventing one build-side. Nothing downstream is left stale: the verdict path reads the column itself, inside the transaction that creates the contact, which no subscriber could do sooner — and records ALREADY captured deliberately keep the filing they have, so there is no batch of rows for an event to announce. The audit row carries the before-image, the word now chosen and which mailbox moved, which is what \"who filed this source under that word, and what was it before\" needs",
	"internal/modules/capture:SetSignatureEnrichment":          "one mailbox's answer to the nightly signature pass is capture POSTURE, not a fact about a record — the same family as capture_settings and the other ADR-0090 configuration surfaces that events.md \u00a75.3c ratifies as audit-only, and the closed catalog (events.md \u00a75) defines no capture_connection.* type for it. Nothing downstream is left stale: the pass reads the column itself in its candidate query on its next run, which no subscriber could do sooner. The audit row carries what the question \"who switched this mailbox off, and what did it say before\" needs — the before-image, the new answer, and the mailbox it belongs to",
	"internal/modules/identity:SaveMyWorkingHours":             "when one person is bookable, which is their own setting and not a record fact. The closed catalog (events.md §5) defines no working-hours type and the closed-verb law forbids inventing one build-side; the nearest, user.locale_changed, is about a different preference and could not carry this one. Nothing downstream is left stale either: availability reads the row on the next question it is asked, which no subscriber could do sooner, and there is no other reader — a booking is refused against the hours as they stand at booking time. The audit images carry both windows, which is what answers the question a host whose bookings halved actually asks",
	"internal/modules/people:recordHumanDomainAdmissionTx":     "blocking a domain or taking one back is capture POSTURE, not a fact about a record — the same family as capture_settings and the other ADR-0090 configuration surfaces that events.md §5.3c ratifies as audit-only, and the closed catalog (events.md §5) defines no domain_disposition.* type for it. Nothing downstream is left stale: the decision is read by the triage sweep from the row itself on its next pass, which no subscriber could do sooner. The audit row carries what the question \"who unblocked this, and what was it before\" needs — the before-image, the new admission, the reason and the human source",
	"internal/modules/people:WriteProviderClaims":              "the arrival of purchased provider values on a person (ADR-0101). Audit-only because the closed catalog (events.md §5) carries no claim verb and the closed-verb law forbids inventing one build-side; person.updated is the nearest candidate and its changed_fields is a REQUIRED, typed, BOUNDED delta over the fields a human patches — a claim is not among them and cannot be expressed as one, so emitting it would publish an empty required delta. The canonical person row is deliberately unchanged too, which is the whole point of keeping claims beside it: announcing person.updated would tell every subscriber a record moved when none did. The audit row is what answers \"which of this subject's records did the provider touch\" — the derivation the provenance rule depends on — and carries the claim KEYS and the run, never the purchased values",
	"internal/modules/integrations:writeStatusThrough":         "the same configuration row again, written by the worker rather than a human: a provider refusal (credential rejected, out of credits, rate limited) recorded on the connection so the settings card states it without a re-probe. Audit-only on the same events.md §5.3c ground as Connect and Disconnect — the closed catalog defines no provider_connection.* type and the closed-verb law forbids inventing one build-side. Nothing downstream is left stale: a run resolves the connection at lease time and reads this status there, sooner than any subscriber could act. The audit image carries what an investigation reads — which provider, which closed safe status code, when — and deliberately carries neither the key nor a balance",
	"internal/modules/identity:applyRoleObjectGrant":           "an admin editing one role's CRUD on one RBAC object. The closed catalog (events.md §5) carries exactly one role verb, role.changed, and its payload is a MEMBER's assignment move (`{user_id, from_role, to_role, by}`, api/public-events.yaml) — it cannot express \"this role's grants moved\" for the unknown set of members who hold it, and the closed-verb law forbids inventing one build-side. Emitting it per holder would also publish a false statement: nobody's assignment changed. Nothing downstream is left stale by the omission either — /me's authorization snapshot is documented as a snapshot rather than an authority, clients refetch it on focus and after any 403, and the gate itself re-resolves the merged policy on every call. The audit row carries the whole fact (actor, role, object, both grant images), which is what a permission-change investigation reads",
	"internal/compose:SaveReportRun":                           "keeping an answer so a report sentence can cite it. The closed catalog (events.md \u00a75, shared/kernel/events/catalog.go) defines no report_run.* or analytics.* type at all, and the closed-verb law forbids inventing one build-side. Nothing downstream is left stale, and this is the strongest form of that claim rather than the usual one: reading a saved run does not serve the stored rows, it RE-ASKS the stored question under the reader's own authority — so a subscriber told \"a run was saved\" could cache nothing, mirror nothing and pre-compute nothing that would not have to be thrown away and recomputed at read time anyway. The saved row is a question plus one reader's view of the answer; it is not a record fact that another system could hold a copy of. The audit row carries what a spend or provenance question reads — which population was asked about, in which schema version, and whether the answer was floored — and deliberately carries neither the rows nor the group keys, because audit_log is append-only and outlives the run, and those rows were narrowed for exactly one person",
	"internal/modules/ai:Record":                               "a human's verdict on a derived claim (AIRT-SCHEMA-1). The closed catalog (events.md \u00a75) defines no ai_feedback.* type and the closed-verb law forbids inventing one build-side. Nothing downstream reacts to a verdict either: the ledger is CONSULTED at re-derivation time, so a subscriber would have nothing to do that the next read does not already do. The audit row carries the attribution a \"corrected by you\" marker and any later dispute both need",
	"internal/modules/assurance:OpenCycle":                     "an operator starting a pass of assurance over a scope. The closed catalog (events.md \u00a75) defines no assurance_cycle.* type and the closed-verb law forbids inventing one build-side. Nothing downstream is left stale either: the only reader is the scan that mints tasks into the cycle, and it resolves the open one from the row on its own next pass. The audit row answers who opened this pass and over what, which is the question an auditor reading a cycle's findings asks first",
	"internal/modules/assurance:CloseCycle":                    "the same pass ending. Audit-only on the same ground, and the moment it closed is already on the row for anything that needs to age it — what the audit adds is WHO decided the window was over, which the closed_at timestamp cannot say",
	"internal/modules/assurance:BundleException":               "one finding joining the cycle's task for its subject. No assurance_task_item.* verb exists, and what a subscriber would actually act on — that a TASK now exists for somebody — is emitted by the activities module's own writer when the caller mints it, so an event here would announce the same act twice. The audit row records which findings a task answers for, which is what a rep disputing a task on their list reads",
	"internal/modules/people:SubmitHandoff":                    "an SDR passing a qualified prospect to an account executive. The closed catalog (events.md \u00a75) defines no sdr_handoff.* type and the closed-verb law forbids inventing one build-side; the nearest verb, lead.promoted, means something else entirely — a lead BECOMING a person, which a handoff neither does nor implies. Nothing downstream is left stale either: the reader is the receiving seat's own queue, which selects open handoffs from the row, so no subscriber could act before the page the AE is looking at. The audit row answers who handed this prospect on and when, which is the question a dispute about credit asks and the one the row itself cannot answer once it is decided",
	"internal/modules/people:ResubmitHandoff":                  "a recycled handoff going back in front of a receiver. Audit-only on exactly the ground SubmitHandoff and DecideHandoff beside it record: the closed catalog defines no sdr_handoff.* verb and the closed-verb law forbids inventing one build-side. Nothing downstream is left stale — the reader is the receiving seat's own queue, which selects open handoffs from the row — and the transition is durable in sdr_handoff_event regardless, written in this same transaction. The audit row answers who put this prospect back in play, which is the question an SDR asking what happened to their handoff reads",
	"internal/modules/people:DecideHandoff":                    "the AE answering it. Audit-only on the same ground as the submission it answers, with one addition: what a subscriber would want — that a DEAL now exists — is already emitted by the deals module's own writer when the acceptance creates one, so an event here would announce the same act twice. The transitions are durable in sdr_handoff_event regardless, written in this same transaction and append-only, so the fact is recorded whether or not anything is published",
	"internal/modules/activities:SetOwedVerdict":               "a classifier's reading of whether one inbound message asks its recipient side for something. The closed catalog (events.md \u00a75) defines no verb for a derived reading of a message, and the closed-verb law forbids inventing one build-side; activity.updated is the only candidate and cannot express it — its changed_fields is a TYPED, bounded struct over the keys UpdateActivity and RelinkActivity patch (api/public-events.yaml), owed_verdict is not among them, and emitting it would publish an empty required delta. Nothing downstream is left stale either: the sole consumer is the waiting queue's own next read, which selects the column in the same statement that ranks the row, so no subscriber could act on the verdict sooner than the page that displays it. The audit row is what answers \"which of a customer's messages did the classifier read and judge\" — the derivation the provenance rule depends on, and the one question a model touching correspondence actually raises",
	"internal/modules/activities:SetReplyVerdict":              "a classifier's reading of whether one inbound message was a positive answer. Audit-only on exactly the ground SetOwedVerdict beside it records, and the load-bearing half was re-checked rather than inherited: activity.updated requires changed_fields and that field is a TYPED, bounded struct over the keys UpdateActivity and RelinkActivity patch (api/public-events.yaml names it PublicEventActivityChangedFields and closes it), reply_verdict is not among them, so emitting would publish an empty required delta. The closed catalog defines no verb for a derived reading of a message and the closed-verb law forbids inventing one build-side. Nothing downstream is left stale: the consumer is whatever computes the rate, which reads the column. The audit row answers \"which of a customer's messages did the classifier read and judge\" — the provenance question a model touching correspondence raises, and the one a rep disputing their own reply rate opens",
	"internal/modules/activities:CorrectReplyVerdict":          "a human disagreeing with that reading. Audit-only for the same reason as the write it corrects — no verb exists, and activity.updated's bounded changed_fields cannot carry reply_verdict — with one addition: the correction is ALREADY durable in activity_reply_verdict_history, written in this same transaction and append-only, so the fact a subscriber might want is recorded whether or not anything is published. The audit row answers who overruled the classifier and when, which is what a later question about a moved rate reads",
	"internal/modules/activities:insertCapturedAttachment":     "a file arriving on a captured message is part of that message, and the capture already emits activity.captured for it in the same transaction. The closed catalog (events.md \u00a75) defines no attachment.* creation type, and the closed-verb law forbids inventing one build-side; announcing the file separately would report one arrival as two. The audit row is still owed and still written — Art. 15 assembly and the audit trail read rows, not events, and a file that reached us with no record of arriving is the gap that matters",
	"internal/modules/capture:auditProjectAttribution":         "the project attribution ladder filing one freshly captured message under a project. Waived on the same ground as insertCapturedAttachment above: the filing is part of that message ARRIVING, and the capture already emitted activity.captured for it moments earlier — announcing it again would report one arrival as two, and every subscriber would react twice. activity.updated is the only candidate type and it belongs to the activities module, which owns what it MEANS (TestEveryEventTypeHasOneEmittingModule); capture does not get to redefine it as \"a message arrived, again\". A consumer of activity.captured may indeed read the activity before this link lands, and that is the design rather than a gap: attribution is optional and most messages get none, so nothing may treat a message's project as settled at arrival. What reads a project's timeline reads activity_link, which is this row. The audit row is still owed and still written: \"how did this message end up on this project\" is exactly the question the ladder raises, and the audit row's principal is what says the ladder rather than a human answered it",
	"internal/modules/activities:RedactCapturedNoiseTx":        "the ADR-0072 noise redaction nulls content on a row that is ALREADY archived, and the one consumer that would not have reacted to the archive — the embedding lane — is handled directly: the redaction deletes the vectors itself, so no subscriber is left holding derived content. The closed catalog (events.md \u00a75) defines no activity.redacted type, and re-announcing an invisible row's content change would tell the rest nothing they can act on",
	"internal/modules/activities:auditIdentityReKey":           "the outbound-send reconcile moves a sent message onto the transport identity its provider actually stamped. activity.updated is the only candidate event and its changed_fields is a REQUIRED, typed, BOUNDED delta over the fields a human patches (subject, body, occurred_at, due_at, remind_at, assignee_id, is_done, a relinked target) — the natural key is not among them and cannot be expressed as one, so emitting it would publish an empty required delta: an event that says a change happened and cannot say what. The closed catalog (events.md §5, shared/kernel/events/catalog.go) defines no transport-identity verb either, and the closed-verb law forbids inventing one build-side. Recorded upstream (P3): the fix is a contract change — a typed identity delta or a discrete reconciliation event — not a build-side substitute",
	"internal/modules/privacy:Create":                          "the retention-policy authoring surface (GCS-WIRE-1..4). The closed catalog (events.md \u00a75) carries retention.applied — the ENGINE's statement that it acted on a RECORD, with that record as the event's entity — and no retention_policy.* type; emitting it for a config edit would publish a claim that a subject's data moved when nothing did. events.md \u00a75.3c ratifies exactly this family as audit-only, the same footing as capture_settings (EVT-NOEVT-3). Nothing downstream is left stale either: the nightly pass re-reads every enabled policy at the start of each run, so the next pass sees the change without being told. The audit row carries both field images, which is what a \"who widened the window?\" investigation reads",
	"internal/modules/privacy:Update":                          "the retention-policy authoring surface (GCS-WIRE-1..4). The closed catalog (events.md \u00a75) carries retention.applied — the ENGINE's statement that it acted on a RECORD, with that record as the event's entity — and no retention_policy.* type; emitting it for a config edit would publish a claim that a subject's data moved when nothing did. events.md \u00a75.3c ratifies exactly this family as audit-only, the same footing as capture_settings (EVT-NOEVT-3). Nothing downstream is left stale either: the nightly pass re-reads every enabled policy at the start of each run, so the next pass sees the change without being told. The audit row carries both field images, which is what a \"who widened the window?\" investigation reads",
	"internal/modules/privacy:Delete":                          "the retention-policy authoring surface (GCS-WIRE-1..4). The closed catalog (events.md \u00a75) carries retention.applied — the ENGINE's statement that it acted on a RECORD, with that record as the event's entity — and no retention_policy.* type; emitting it for a config edit would publish a claim that a subject's data moved when nothing did. events.md \u00a75.3c ratifies exactly this family as audit-only, the same footing as capture_settings (EVT-NOEVT-3). Nothing downstream is left stale either: the nightly pass re-reads every enabled policy at the start of each run, so the next pass sees the change without being told. The audit row carries both field images, which is what a \"who widened the window?\" investigation reads",
	"internal/modules/activities:setDealDocumentHidden":        "hiding or unhiding a captured file on ONE deal's Files area. The file, the message and the company library are untouched — the row only says which deal lists it — and the closed catalog defines no attachment.* type, on the same ground as UploadAttachment and ArchiveAttachment above. The audit row names the deal and the attachment, which answers \"who took this off the deal\"",
	"internal/modules/dealrooms:PreviewRoom":                   "the seller looking at their own room as a buyer. The preview seat is the seller's own and invisible to buyers; the catalog's participant_invited and credential_reissued events are about buyers being admitted, and announcing a rep's preview as one would count the rep as an invited buyer in every subscriber. The audit row names the seat and says preview",
	"internal/modules/dealrooms:NoteLinkRequest":               "a buyer asking the public page for a new link, stamped on their seat so the seller can see the ask and hand over a link when no mail can go. Nothing about the room or its content changed — the audit row names the seat and the anonymous requester, and the closed catalog announces credentials only when one is actually reissued (deal_room.participant_credential_reissued, which the reissue half of the same call still emits)",
	"internal/modules/signals:NarrowDerivedForActivity":        "the audience-change corrector narrowing a derived signal to its capture owner (or archiving an ownerless one). The closed catalog (events.md §5) carries signal.detected and signal.resolved, neither of which says \"this summary's audience narrowed\", and the closed-verb law forbids inventing one build-side — announcing the narrowing would also broadcast the existence of what a human just limited. The signal surfaces read the rows, and the same transaction drops the thread's scan watermark so the next extraction pass re-reads under the new audience; the ONE deliberate asymmetry is that a WIDENED activity never widens an already-narrowed signal — its live fingerprint blocks a duplicate, and disclosure is the direction that must never happen by side effect. The audit row answers \"why did this summary vanish from my colleagues' view\"",
	"internal/modules/knowledge:DeleteDocument":                "destroying a document, its passages, its vectors and its stored file. The closed catalog (events.md \u00a75) defines no knowledge_document.* type and the closed-verb law forbids inventing one build-side \u2014 the same ground as the upload it undoes, and it would be strange for the arrival to announce nothing and the removal to announce something. Nothing downstream is left stale: the passages are GONE in the same transaction, so the ask cannot retrieve them on its next question whether or not anyone was told, and the corpus's coverage counts are computed from the rows at read time. The audit row is the whole point of this write and is pinned to four keys \u2014 filename, checksum, content_type, chunk_count \u2014 because audit_log is append-only and outlives the deletion, so a chunk of document text in the image would stay readable through field history, record history and the compliance log after the document was destroyed",
	"internal/modules/knowledge:UploadDocument":                "a file arriving in a corpus. The closed catalog (events.md \u00a75) defines no knowledge_document.* type and the closed-verb law forbids inventing one build-side \u2014 the same ground as insertCapturedAttachment, and for the same reason: an attachment arriving is not a record moving. Nothing downstream is left stale either, and this one is stronger than the usual form of that claim: the ONE consumer that must learn about the upload is the ingest job, and it is enqueued in this SAME transaction carrying the document id. A subscriber could not act sooner than a job that is already queued when the row commits. The audit row is still owed and still written \u2014 \"who put this third party's prose into the body every seat now asks\" is exactly the question a corpus raises \u2014 and it carries the filename, type and size, never the document's text",
	"internal/modules/knowledge:WriteChunks":                   "one ingest attempt recording the passages it cut. Chunks are a DERIVED artifact of a document that already exists \u2014 the same species as an embedding, which this tree also announces to nobody \u2014 and the closed catalog carries no verb for one. Nothing downstream could use it: the corpus's coverage counts are computed from the rows at read time, and the ask resolves its passages at question time, so a subscriber told \"chunks were written\" has nothing to do that the next read does not already do. The audit row goes on the DOCUMENT and carries only the count, before and after \u2014 never the passages, because an audit image is append-only and would outlive the delete that clears them",
	"internal/modules/knowledge:FailIngest":                    "an ingest giving up after its attempts are exhausted. Same absence of a knowledge_document.* verb, and nothing was ever announced to retract \u2014 the arrival emitted nothing either. The only reader of a failed ingest is the person who uploaded the file, and they read the row: ingest_status and ingest_detail are on the document the corpus screen already lists. The audit row carries both status images and the reason, which is what answers \"why is this file not in the corpus\"",
	"internal/modules/knowledge:ensureHandbookCorpus":          "defining a document corpus is workspace CONFIGURATION in the events.md \u00a75.3c family, and the closed catalog (events.md \u00a75) defines no knowledge_corpus.* or knowledge_document.* type \u2014 exactly the ground CreateCorpus and UploadDocument beside it are ratified on, and this writes the same two entities. It creates the shipped handbook corpus the first time a release boots. Nothing downstream is left stale: the ask resolves the corpus and its floor at question time from the row, so a subscriber could not act sooner than the next question already does. The audit row is what answers \"where did this corpus nobody created come from\" \u2014 it names the release's own system actor rather than a person, which is the whole point of recording it",
	"internal/modules/knowledge:reconcilePages":                "defining a document corpus is workspace CONFIGURATION in the events.md \u00a75.3c family, and the closed catalog (events.md \u00a75) defines no knowledge_corpus.* or knowledge_document.* type \u2014 exactly the ground CreateCorpus and UploadDocument beside it are ratified on, and this writes the same two entities. This is the removal half: a page an earlier release shipped and this one withdrew. Nothing was ever announced to retract, because filePage announces nothing either, and the passages are GONE in the same transaction \u2014 so the ask cannot retrieve them on its next question whether or not anyone was told. The audit row names the filename and the managed source, which is what answers \"why did the handbook stop citing that page\"",
	"internal/modules/knowledge:filePage":                      "defining a document corpus is workspace CONFIGURATION in the events.md \u00a75.3c family, and the closed catalog (events.md \u00a75) defines no knowledge_corpus.* or knowledge_document.* type \u2014 exactly the ground CreateCorpus and UploadDocument beside it are ratified on, and this writes the same two entities. A page of the handbook arriving is an attachment arriving, not a record moving \u2014 the same ground as UploadDocument, and the same stronger form of the no-stale-subscriber claim: the ONE consumer that must learn about it is the ingest job, enqueued in this SAME transaction carrying the document id. The audit row carries the filename, type and size, never the page's prose",
	"internal/modules/knowledge:replacePage":                   "defining a document corpus is workspace CONFIGURATION in the events.md \u00a75.3c family, and the closed catalog (events.md \u00a75) defines no knowledge_corpus.* or knowledge_document.* type \u2014 exactly the ground CreateCorpus and UploadDocument beside it are ratified on, and this writes the same two entities. A release rewording a page it already ships. Same absence of a verb, and the same in-transaction ingest is the only consumer that had to learn. The audit image carries the checksum it moved FROM, which is what answers \"which release changed the wording the answer I was given quoted\" \u2014 the question a citation into shipped prose actually raises",
	"internal/modules/knowledge:clearDefaultAsk":               "the corpus that LOSES the default-ask flag when another takes it. Audit-only on exactly the same ground as the CreateCorpus and EditCorpus calls that reach it \u2014 a corpus is workspace configuration in the events.md \u00a75.3c family and the closed catalog carries no knowledge_corpus.* verb. It is listed SEPARATELY because it is a second ENTITY mutated inside an audited call: the write-shape gate reads one entry point at a time and cannot see it, and the audit row it writes is the demoted corpus's own \u2014 without which that corpus's history never says its flag moved or who moved it, and \"why did the palette stop asking my set\" is unanswerable from the trail",
	"internal/modules/knowledge:CreateCorpus":                  "defining a document corpus, editing its words and moving its grounding floor are workspace CONFIGURATION, not facts about a record \u2014 the same events.md \u00a75.3c family as saved views, lists, retention policies and the lead vocabularies, and the closed catalog (events.md \u00a75) defines no knowledge_corpus.* type. The closed-verb law forbids inventing one build-side, and no existing verb comes close: the nearest shapes are all statements that a SUBJECT's record moved, and nobody's record moves when an admin renames a corpus. Nothing downstream is left stale either \u2014 the ask resolves the corpus and its floor at question time, from the row, so a subscriber could not act on the change any sooner than the next question already does; and the ingest that would care about an archive re-reads the document's own archived_at inside its write transaction rather than waiting to be told. The audit row carries both field images, which is what answers the question this surface actually raises: \"who moved the floor, and what would we have answered before?\"",
	"internal/modules/knowledge:EditCorpus":                    "defining a document corpus, editing its words and moving its grounding floor are workspace CONFIGURATION, not facts about a record \u2014 the same events.md \u00a75.3c family as saved views, lists, retention policies and the lead vocabularies, and the closed catalog (events.md \u00a75) defines no knowledge_corpus.* type. The closed-verb law forbids inventing one build-side, and no existing verb comes close: the nearest shapes are all statements that a SUBJECT's record moved, and nobody's record moves when an admin renames a corpus. Nothing downstream is left stale either \u2014 the ask resolves the corpus and its floor at question time, from the row, so a subscriber could not act on the change any sooner than the next question already does; and the ingest that would care about an archive re-reads the document's own archived_at inside its write transaction rather than waiting to be told. The audit row carries both field images, which is what answers the question this surface actually raises: \"who moved the floor, and what would we have answered before?\"",
	"internal/modules/knowledge:ArchiveCorpus":                 "defining a document corpus, editing its words and moving its grounding floor are workspace CONFIGURATION, not facts about a record \u2014 the same events.md \u00a75.3c family as saved views, lists, retention policies and the lead vocabularies, and the closed catalog (events.md \u00a75) defines no knowledge_corpus.* type. The closed-verb law forbids inventing one build-side, and no existing verb comes close: the nearest shapes are all statements that a SUBJECT's record moved, and nobody's record moves when an admin renames a corpus. Nothing downstream is left stale either \u2014 the ask resolves the corpus and its floor at question time, from the row, so a subscriber could not act on the change any sooner than the next question already does; and the ingest that would care about an archive re-reads the document's own archived_at inside its write transaction rather than waiting to be told. The audit row carries both field images, which is what answers the question this surface actually raises: \"who moved the floor, and what would we have answered before?\"",
	"internal/modules/collections:CreateSavedView":             "saved views are per-user view state, not record facts — events.md §5.3c ratifies this config family as audit-only and defines no saved_view.* type",
	"internal/modules/collections:UpdateSavedView":             "saved views are per-user view state, not record facts — events.md §5.3c ratifies this config family as audit-only and defines no saved_view.* type",
	"internal/modules/collections:ArchiveSavedView":            "saved views are per-user view state, not record facts — events.md §5.3c ratifies this config family as audit-only and defines no saved_view.* type",
	"internal/modules/collections:CreateList":                  "lists are ratified audit-only in V1 — events.md \u00a75.3c defines no list.* types and none is added",
	"internal/modules/collections:ArchiveList":                 "lists are ratified audit-only in V1 — events.md \u00a75.3c defines no list.* types and none is added",
	"internal/modules/collections:AddMember":                   "lists are ratified audit-only in V1 — events.md \u00a75.3c defines no list.* types and none is added",
	"internal/modules/collections:CreateTag":                   "tags are ratified audit-only in V1 — events.md \u00a75.3c defines no tag.* types and none is added",
	"internal/modules/collections:ArchiveTag":                  "tags are ratified audit-only in V1 — events.md \u00a75.3c defines no tag.* types and none is added",
	"internal/modules/collections:UpdateTag":                   "a tag is workspace vocabulary, not a record fact: the closed event catalog carries no tag.* type and none is added here, because a subscriber acts on the RECORD a tag was applied to and that write emits its own event. The audit row answers who changed the word, which is the question a vocabulary dispute asks",
	"internal/modules/collections:RestoreTag":                  "a tag is workspace vocabulary, not a record fact: the closed event catalog carries no tag.* type and none is added here, because a subscriber acts on the RECORD a tag was applied to and that write emits its own event. The audit row answers who changed the word, which is the question a vocabulary dispute asks",
	"internal/modules/collections:MergeTags":                   "a tag is workspace vocabulary, not a record fact: the closed event catalog carries no tag.* type and none is added here, because a subscriber acts on the RECORD a tag was applied to and that write emits its own event. The audit row answers who changed the word, which is the question a vocabulary dispute asks",
	"internal/modules/collections:applyTagTx":                  "tags are ratified audit-only in V1 — events.md \u00a75.3c defines no tag.* types and none is added",
	"internal/modules/collections:RemoveTag":                   "the same ratification as ApplyTag beside it: tags are audit-only in V1, events.md \u00a75.3c defines no tag.* types, and taking a tag off does not become an event because putting one on is not",
	"internal/modules/consent:CreateDSR":                       "the closed catalog (events.md \u00a75) defines no dsr.* type; the closed-verb law forbids inventing one build-side",
	"internal/modules/consent:UpdateDSR":                       "the closed catalog (events.md \u00a75) defines no dsr.* type; the closed-verb law forbids inventing one build-side",
	"internal/modules/consent:finalizeErasureFulfil":           "the audit-only finalize step of FulfilErasure: the closed catalog (events.md \u00a75) defines no dsr.* type; the closed-verb law forbids inventing one build-side (the erase side effect emits its own person.* event inside privacy.ErasePerson)",
	"internal/modules/consent:issueLink":                       "minting the confirm-details link, audit-only because the closed catalog defines no consent.confirm_issued type and the closed-verb law forbids inventing one build-side. Nothing downstream is left stale — what a subscriber would care about is the ANSWER, and when it arrives Record emits consent.changed for it. The audit row carries which subject and which address the link went to, which is the evidence a grant made through it rests on",
	"internal/modules/consent:stageSubmission":                 "a data subject proposing a correction to their own record through the confirm link. The closed catalog defines no confirm_submission.* type, and the nearest verbs would both be lies: person.updated would announce a change to a record nothing changed, and approval.requested belongs to the staging engine this deliberately does not use. Nothing downstream can act on it either — only a human accepting the proposal moves anything, and that acceptance emits its own event. The audit row answers \"what did this contact send us, and when\"",
	"internal/modules/automation:Create":                       "automation config is ratified audit-only \u2014 the closed catalog (events.md \u00a75) defines no automation.* type; the runs it produces are separately recorded in workflow_run",
	"internal/modules/automation:Update":                       "automation config is ratified audit-only \u2014 the closed catalog (events.md \u00a75) defines no automation.* type; the runs it produces are separately recorded in workflow_run",
	"internal/modules/automation:Archive":                      "automation config is ratified audit-only \u2014 the closed catalog (events.md \u00a75) defines no automation.* type; the runs it produces are separately recorded in workflow_run",
	"internal/modules/webhooks:CreateSubscription":             "webhook-subscription config is ratified audit-only \u2014 the closed catalog (events.md \u00a75) defines no webhook_subscription.* type; the deliveries it produces are separately recorded in webhook_delivery",
	"internal/modules/webhooks:UpdateSubscription":             "webhook-subscription config is ratified audit-only \u2014 the closed catalog (events.md \u00a75) defines no webhook_subscription.* type; the deliveries it produces are separately recorded in webhook_delivery",
	"internal/modules/webhooks:RotateSecret":                   "webhook-subscription config is ratified audit-only \u2014 the closed catalog (events.md \u00a75) defines no webhook_subscription.* type; the rotation is attributable via its audit row",
	"internal/modules/webhooks:ArchiveSubscription":            "webhook-subscription config is ratified audit-only \u2014 the closed catalog (events.md \u00a75) defines no webhook_subscription.* type; archive stops delivery and is attributable via its audit row",
	"internal/modules/webhooks:requireReplay":                  "a human-initiated delivery replay is ratified audit-only \u2014 it re-attempts an existing webhook_delivery; the closed catalog (events.md \u00a75) defines no webhook.* type",
	"internal/modules/capture:Set":                             "one seat's decision about a sender — capture config on the same ruling as the exclusion list below (EVT-NOEVT-3): the closed catalog defines no verb for a list entry, and the closed-verb law forbids inventing one build-side. Nothing downstream is left stale either, because the decision is read at the point it matters — the verdict engine consults it inside the transaction that judges the sender",
	"internal/modules/capture:Add":                             "the workspace consumer-mail, own-domain and exclusion lists are capture config, ratified audit-only on the same ruling as the capture-settings write (EVT-NOEVT-3): the closed catalog (events.md \u00a75) defines no verb for a list entry, and the closed-verb law forbids inventing one build-side",
	"internal/modules/capture:Remove":                          "withdrawing a consumer-mail, own-domain, exclusion or sender-decision list entry, same ratified audit-only posture as Add. The key names the METHOD, so every capture list's Remove is covered by this one line — they are the same act on the same kind of configuration row",
	"internal/platform/settings:SetRawTx":                      "an installation-settings write is ratified audit-only (EVT-NOEVT-3, ADR-0090/A135) \u2014 the closed catalog (events.md \u00a75) defines no settings type, and the closed-verb law forbids inventing one build-side. This is the SAME ruling the capture-settings write carried before ADR-0090 moved it here, generalized: it now covers every setting rather than one column, so a new setting inherits the posture instead of arguing it again. A setting whose change genuinely needs a consumer is the case for adding a catalog verb upstream, not for emitting an unlisted one here",
	"internal/modules/capture:auditLifecycle":                  "connector lifecycle (connect/reconnect/disconnect) is audit-only because the kernel models NO entity kind for capture_connection \u2014 storekit.Emit needs one, and the closed catalog (events.md \u00a75) defines no connector.* type. Inventing one build-side would break the closed-verb law. Attribution, which is what the privacy boundary actually needs, is carried by the audit row",
	"internal/modules/deals:CreateProduct":                     "the rate-card is ratified audit-only \u2014 the closed catalog (events.md \u00a75) defines no product.* type and the closed-verb law forbids inventing one build-side",
	"internal/modules/deals:UpdateProduct":                     "the rate-card is ratified audit-only \u2014 the closed catalog (events.md \u00a75) defines no product.* type and the closed-verb law forbids inventing one build-side",
	"internal/modules/deals:ArchiveProduct":                    "the rate-card is ratified audit-only \u2014 the closed catalog (events.md \u00a75) defines no product.* type and the closed-verb law forbids inventing one build-side",
	"internal/modules/deals:UpdateOffer":                       "draft-offer edits are ratified audit-only \u2014 events.md \u00a75.3 defines only lifecycle offer.* types (created/sent/accepted/rejected/superseded), no offer.updated",
	"internal/modules/deals:ArchiveOffer":                      "offer archive is ratified audit-only \u2014 events.md \u00a75.3 defines no offer.archived type and the closed-verb law forbids inventing one build-side",
	"internal/modules/deals:SetPdfAssetRef":                    "persisting the rendered PDF's blob ref is ratified audit-only \u2014 events.md \u00a75.3 defines only lifecycle offer.* types, no offer.rendered, and the closed-verb law forbids inventing one build-side",
	"internal/modules/deals:AddOfferLineItem":                  "draft line edits are ratified audit-only \u2014 events.md \u00a75.3 defines only lifecycle offer.* types, no offer.updated",
	"internal/modules/deals:UpdateOfferLineItem":               "draft line edits are ratified audit-only \u2014 events.md \u00a75.3 defines only lifecycle offer.* types, no offer.updated",
	"internal/modules/deals:RemoveOfferLineItem":               "draft line edits are ratified audit-only \u2014 events.md \u00a75.3 defines only lifecycle offer.* types, no offer.updated",
	"internal/modules/deals:AcceptOfferLineItem":               "accepting a staged draft line (E03.21a) is a draft line edit \u2014 events.md \u00a75.3 defines only lifecycle offer.* types, no offer.updated",
	"internal/modules/deals:AddStagedOfferLines":               "staging AI-drafted draft lines (E03.21a) is a draft line edit \u2014 events.md \u00a75.3 defines only lifecycle offer.* types, no offer.updated; a staged line is invisible until AcceptOfferLineItem, which carries the same ratified waiver",
	"internal/modules/deals:CreateOfferTemplate":               "offer templates are workspace-authored config, the Product precedent \u2014 the closed catalog (events.md \u00a75) defines no offer_template.* type and the closed-verb law forbids inventing one build-side",
	"internal/modules/deals:UpdateOfferTemplate":               "offer templates are workspace-authored config, the Product precedent \u2014 the closed catalog (events.md \u00a75) defines no offer_template.* type and the closed-verb law forbids inventing one build-side",
	"internal/modules/deals:ArchiveOfferTemplate":              "offer templates are workspace-authored config, the Product precedent \u2014 the closed catalog (events.md \u00a75) defines no offer_template.* type and the closed-verb law forbids inventing one build-side",
	"internal/modules/people:setDedupeDispositionTx":           "the queue verdict is review-flow state, not a record fact \u2014 the closed catalog (events.md \u00a75) defines no dedupe.* type; the merge arm's person.merged/organization.merged carries the bus-visible outcome",
	"internal/modules/people:reopenDedupeCandidateTx":          "the queue verdict is review-flow state, not a record fact \u2014 the closed catalog (events.md \u00a75) defines no dedupe.* type; the merge arm's person.merged/organization.merged carries the bus-visible outcome",
	"internal/modules/identity:CreateRecordGrant":              "the closed catalog (events.md \u00a75) defines no grant.* type; the closed-verb law forbids inventing one build-side",
	"internal/modules/identity:RevokeRecordGrant":              "the closed catalog (events.md \u00a75) defines no grant.* type; the closed-verb law forbids inventing one build-side",
	"internal/modules/identity:mintPassport":                   "minting an Agent Seat Passport is ratified audit-only \u2014 the closed catalog (events.md \u00a75.6a) defines passport.revoked and NO issuance counterpart, so the only bus-visible passport fact is its death. That asymmetry is deliberate on the consumer side (a long-lived holder must drop a credential that died; nobody has to react to one being born) and the closed-verb law forbids inventing passport.issued build-side. The mint is attributable via its audit row; the missing type is raised upstream (P3)",
	"internal/modules/identity:mintConsentedAuthorizationCode": "the record of WHICH scopes a human ticked and granted to a client is ratified audit-only — the closed catalog (events.md §5) defines no consent fact at all, and the one type that would fit structurally, audit.appended, is declared in the contract as having no emit site and an EMPTY payload, so it could name neither the scopes nor the client. It sits beside issueGrant and mintPassport, the two credential writes this same consent produces when the code is redeemed, and carries the same waiver for the same reason; the addition (an OAuth-consent verb covering the grant, the issuance and the revoke cascade) is raised upstream (P3)",
	"internal/modules/signals:AcknowledgeTx":                   "the same ratified audit-only posture as UpdateSignal, whose triage path this is the approval-effect twin of \u2014 events.md \u00a75.11 defines only signal.detected/signal.resolved, no signal.updated, and the closed-verb law forbids inventing one build-side",
	"internal/modules/signals:UpdateSignal":                    "human triage (status/severity) is ratified audit-only \u2014 events.md \u00a75.11 defines only signal.detected/signal.resolved (raw\u2192entity attribution, emitted by the resolver), no signal.updated, and the closed-verb law forbids inventing one build-side",
	"internal/modules/signals:ArchiveSignal":                   "signal archive is ratified audit-only \u2014 events.md \u00a75.11 defines no signal.archived type and the closed-verb law forbids inventing one build-side",
	"internal/modules/activities:UploadAttachment":             "attachments are ratified audit-only \u2014 the closed catalog (events.md \u00a75) defines no attachment.* type and a polymorphic attachment has no single stream to ride; the closed-verb law forbids inventing one build-side",
	"internal/modules/activities:ArchiveAttachment":            "attachments are ratified audit-only \u2014 the closed catalog (events.md \u00a75) defines no attachment.* type and a polymorphic attachment has no single stream to ride; the closed-verb law forbids inventing one build-side",
	"internal/modules/activities:UpdateAttachmentMetadata":     "attachments are ratified audit-only \u2014 the closed catalog (events.md \u00a75) defines no attachment.* type and a polymorphic attachment has no single stream to ride; the closed-verb law forbids inventing one build-side. This write sets what a document MEANS (category, title, state, pin) and moves no bytes, so it has even less to publish than the upload beside it",
	"internal/modules/customfields:createInTx":                 "the closed catalog (events.md \u00a75) defines no custom_field.* type \u2014 the spec's custom-fields.md \u00a7Events ratifies the audit entry as the add/rename/retire trail, and a cross-object catalog change has no single family stream to ride (the attachments precedent)",
	"internal/modules/customfields:Rename":                     "the closed catalog (events.md \u00a75) defines no custom_field.* type \u2014 the spec's custom-fields.md \u00a7Events ratifies the audit entry as the add/rename/retire trail",
	"internal/modules/customfields:Retire":                     "the closed catalog (events.md \u00a75) defines no custom_field.* type \u2014 the spec's custom-fields.md \u00a7Events ratifies the audit entry as the add/rename/retire trail",
	"internal/modules/customfields:setOptionsInTx":             "the closed catalog (events.md \u00a75) defines no custom_field.* type \u2014 the spec's custom-fields.md \u00a7Events ratifies the audit entry as the add/rename/retire trail",
	"internal/modules/ai:writeModelRate":                       "model prices are ratified audit-only (EVT-NOEVT-3) \u2014 the closed catalog (events.md \u00a75) defines no ai_model_rate.* type and the price sheet is workspace config recomputed price-on-read, the same ruling as the deals-owned product rate-card; inventing a build-side type or stream would violate the closed catalog (P3)",
	"internal/modules/deals:writeFxRate":                       "FX rates are ratified audit-only (EVT-NOEVT-3) \u2014 the closed catalog (events.md \u00a75) defines no fx_rate.* type and the rate sheet is workspace config recomputed price-on-read, the same ruling as the deals-owned product rate-card (CreateProduct is audit-only); an fx_rate.* verb on the deal stream would be a build-side invention the closed catalog forbids (P3)",
	"internal/modules/privacy:AssembleSAR":                     "the closed catalog (events.md \u00a75) defines no subject-access-export type; the export is a read whose only write IS the audit row",
	"internal/modules/privacy:tombstoneCollateralScrubs":       "the erasure's single retention.applied on the person is the bus-visible fact for the whole scrub; these tombstones exist to bound each collateral record's field-history projection, and the closed catalog (events.md \u00a75) defines no per-collateral erasure type to ride",
	"internal/modules/overlay:auditUserMapChange":              "the Margince-user <-> incumbent-user mapping is workspace config, not a record fact: mirror_user_map is not a public contract entity, and the closed catalog (events.md §5, shared/kernel/events/catalog.go) defines no mirror.user_* type. Emitting one would need a contract event with no consumer. Same audit-only posture as overlay's own mode flip",
	"internal/modules/overlay:BlockAutoMap":                    "an admin's deliberate unmap is a workspace-config change on mirror_user_map and its standing mirror_user_automap_block, neither of them a public contract entity — the closed catalog defines no mirror.user_* type for either the removed mapping or the block that replaces it. Same audit-only posture as UpsertUserMap",
	"internal/modules/overlay:auditRevokedMappings":            "an automated mapping revoke — a stale email-sourced row, or one whose incumbent owner email became ambiguous — is a workspace-config change on mirror_user_map, which is not a public contract entity: the closed catalog defines no mirror.user_* type. Audited so a user's silently-removed access has a record; same posture as UpsertUserMap",
	"internal/modules/migration:Create":                        "import-run lifecycle is ratified audit-only \u2014 the import-export-migration chapter's IEM-GAP-3 explicitly declines to invent run-lifecycle events build-side ('this chapter deliberately does not invent them here'); the rows the run lands emit their own standard entity events through the native stores",
	"internal/modules/migration:CreateStagedRun":               "the direct importer's half of the same ratified import-run lifecycle \u2014 IEM-GAP-3 declines run-lifecycle events build-side, and the staged states it adds (validating, awaiting_approval) are the ones a human polls through IEM-WIRE-6 rather than subscribing to; the leads and organizations the approved run lands emit their own entity events through the people store. See migration:Create",
	"internal/modules/migration:FailValidation":                "the staged lifecycle's failure arm, audit-only on the same ground as its sibling moves: IEM-GAP-3 defines no run-lifecycle event and the closed-verb law forbids inventing one build-side. It records a validation that could not finish, which wrote nothing to the estate for a subscriber to hear about. See migration:Create",
	"internal/modules/migration:stageTransition":               "the staged lifecycle's one move (validating\u2192awaiting_approval\u2192running), audit-only on exactly the ground migration:transition already is: IEM-GAP-3 defines no run-lifecycle event and the closed-verb law forbids inventing one build-side. The audit row carries both sides of the move, which is what answers \"who approved this import, and against which state\"",
	"internal/modules/migration:Resume":                        "import-run lifecycle is ratified audit-only \u2014 IEM-GAP-3 declines run-lifecycle events build-side; see migration:Create",
	"internal/modules/migration:transition":                    "import-run lifecycle is ratified audit-only \u2014 IEM-GAP-3 declines run-lifecycle events build-side; see migration:Create",
	"internal/modules/migration:beginUndo":                     "the undo lifecycle's own start move (complete\u2192undoing, or resuming one already undoing), audit-only on exactly the ground migration:transition already is: IEM-GAP-3 defines no run-lifecycle event and the closed-verb law forbids inventing one build-side. See migration:Create",
	"internal/modules/migration:completeUndo":                  "the undo lifecycle's finish move (undoing\u2192undone), same ground as beginUndo \u2014 IEM-GAP-3 declines run-lifecycle events build-side. The rows it reverses are archived through each object's OWN store method, which emits its own standard entity event; this row is the import_run's own bookkeeping, exactly like the forward commit's completion. See migration:Create",
	"internal/modules/overlay:auditFreeze":                     "the flip's mirror freeze/unfreeze is audit-only for the same reason CompleteFlip is: the closed catalog (events.md §5) defines no mirror-freeze or flip.* type, and the freeze's observable effect is local (fenced writes refuse, the sweep skips the workspace) — no subscriber could act on an event. Audited because halting incumbent sync is a governance-relevant act and who latched the workspace must be on the record",
	"internal/modules/overlay:CompleteFlip":                    "the overlay\u2192native mode flip is audit-only by the same ruling as overlay's Connect/Disconnect mode writes carry their connection events: the closed catalog (events.md \u00a75) defines no flip.* or workspace-mode type, ADR-0071 mints no event, and the flip's observable effect (the dispatcher re-route) rides the in-process mode-flip observer, not the bus. The audit row carries the run id + mode",
	"internal/compose:auditExport":                             "the export audit entry IS the deliverable (features/04 \u00a75: 'writes the single export audit entry'; IEM 'export emits no domain events') \u2014 the closed catalog defines no export.* type and the bundle mutates no record",
	"internal/compose:sweepAndReseed":                          "the non-production admin data-reset's own audit row records the reset operation itself (entity_type workspace) \u2014 the closed catalog (events.md \u00a75) defines no reset.* type, and a subscriber would learn nothing actionable from an event announcing that the workspace it was about to react to no longer has the rows it referenced. The re-seed the same transaction performs writes its own standard entity events through each module's native seeder (pipeline.created, etc.)",
	"internal/compose/weekly:insertReview":                     "one rep's weekly retrospective, on the same ground as the brief run beside it: the closed catalog (events.md \u00a75) defines no weekly_review.* type and the closed-verb law forbids inventing one build-side. Nothing downstream is left stale either — the only reader is the rep opening the review, and a subscriber could not tell them sooner than the screen they are already on. The audit row answers \"which week was measured, and to what instant\", which is what a retrospective's own provenance question asks",
	"internal/compose/weekly:RecordLearnings":                  "what a week TAUGHT, frozen onto the review once. Audit-only on exactly the ground insertReview and writeOutlook state: the closed catalog (events.md \u00a75) defines no weekly_review.* type and the closed-verb law forbids inventing one build-side. Nothing downstream is left stale — the only reader is the rep opening their own retrospective — and the audit row answers whether the week was learned from and how many learnings it holds, which is what somebody asking why a past week shows no lessons reads",
	"internal/compose/weekly:writeOutlook":                     "where a closed week was landing, frozen onto the review in the same transaction that writes it. Audit-only on exactly the ground insertReview states: the closed catalog (events.md \u00a75) defines no weekly_review.* type and the closed-verb law forbids inventing one build-side. A forecast verb would be the wrong thing to want too — nothing here CHANGES a forecast, it copies figures a snapshot already published, and forecast_snapshot.created ships from the snapshot this same pass takes, so a second event would report one reading twice. Nothing downstream is left stale: the only reader is the rep opening their own retrospective. The audit row answers how many horizons and bars this week froze, which is what somebody asking why a past week draws no bridge reads",
	"internal/compose/weekly:Narrate":                          "the sentence a model wrote over a week's counts, on the same ground as the review it lands on: the closed catalog (events.md \u00a75) defines no weekly_review.* type and the closed-verb law forbids inventing one build-side. Nothing downstream is left stale — the only reader is the rep opening the review — and the audit row carries the sentence and the stamp it replaced",
	"internal/compose/weekly:ClaimMailAttempt":                 "taking the one SMTP attempt a rep's weekly is allowed, on the same ground as the review it claims: the closed catalog (events.md \u00a75) defines no weekly_review.* type and the closed-verb law forbids inventing one build-side. It is also the one write in this arc where an event would be actively wrong — the claim exists to bound duplicate MAIL, so publishing it to an at-least-once bus whose consumers are told to expect redelivery would hand the next author the exact re-send this design refuses. Nothing downstream is left stale: the only reader is the same job, in the same tick, from the row it just wrote. The audit row answers \"was this week ever attempted, and when\", which is what somebody asking where their weekly went reads",
	"internal/compose/weekly:MailFailed":                       "why that spent attempt produced no message. Audit-only on the same ground as the claim it annotates, and for the same reason more sharply: the row records a mail that did NOT go out, and there is no verb in the closed catalog for an absence. Nothing can act on it either — the attempt is spent by design and no retry follows — so the audit row and the column beside it are the whole answer to \"where is my weekly\"",
	"internal/compose/briefs:MailFailed":                       "why that spent attempt produced no morning message. Audit-only on the same ground as the claim it annotates, and for the same reason more sharply: the row records a mail that did NOT go out, and there is no verb in the closed catalog for an absence. Nothing can act on it either — the attempt is spent by design and no retry follows — so the audit row and the column beside it are the whole answer to \"where is my brief\"",
	"internal/compose/briefs:ClaimMailAttempt":                 "taking the one SMTP attempt a rep's morning brief is allowed, on exactly the ground the weekly's claim above states: the brief read model is ratified audit-only, the closed catalog (events.md \u00a75) defines no brief.* type and the closed-verb law forbids inventing one build-side. It is also the one write in this arc where an event would be actively wrong — the claim exists to bound duplicate MAIL, so publishing it to an at-least-once bus whose consumers are told to expect redelivery would hand the next author the exact re-send this design refuses, and this lane runs five mornings a week where the weekly runs once. Nothing downstream is left stale: the only reader is the same job, in the same tick, from the row it just wrote. The audit row answers \"was this morning ever attempted, and when\", which is what somebody asking where their brief went reads",
	"internal/compose/briefs:SnapshotRunForDay":                "the brief read model is ratified audit-only \u2014 the closed catalog (events.md \u00a75) defines no brief.* type and the closed-verb law forbids inventing one build-side",
	"internal/compose/briefs:markItem":                         "the brief read model is ratified audit-only \u2014 the closed catalog (events.md \u00a75) defines no brief.* type and the closed-verb law forbids inventing one build-side",
	"internal/compose/briefs:MarkUnsnoozed":                    "taking back a snooze, on exactly the ground markItem above it stands on: the brief read model is ratified audit-only, the closed catalog (events.md \u00a75) defines no brief.* type and the closed-verb law forbids inventing one build-side. It is the mirror of a write already waived here, so an event on the way back and none on the way in would describe half a round trip. Nothing downstream is left stale — the only reader is the rep whose queue it is, looking at the screen that just posted it — and the audit row carries the snooze it cleared, which answers \"why did this come back\"",
	"internal/compose/briefs:annotateItem":                     "the overnight agent's finding on one queued deal, on the same ground as markItem beside it: the brief read model is ratified audit-only, the closed catalog (events.md \u00a75) defines no brief.* type and the closed-verb law forbids inventing one build-side. Nothing downstream is left stale either — the only reader is the person opening Home, who reads the row itself, and a subscriber could not tell them sooner than the screen they are already looking at. The audit row carries both images, which is what answers \"what did the night say about this deal, and what did it say before\"",
	"internal/compose/briefs:writeRunNarrative":                "the same pass's sentence about the night as a whole, waived on identical ground to annotateItem: no brief.* verb exists in the closed catalog, the only reader is Home, and the audit row carries the sentence and the stamp it replaced",
	"internal/compose/briefs:clearFindings":                    "the same pass erasing what the previous one said before writing its own, on identical ground: no brief.* verb exists in the closed catalog, the only reader is Home, and the erasure is one half of a replacement whose other half is audited beside it. The audit row records how many findings the pass cleared, which answers \"did tonight's pass drop yesterday's explanations\"",
	"internal/compose/briefs:resurfaceExpiredSnoozes":          "the brief read model is ratified audit-only \u2014 the closed catalog (events.md \u00a75) defines no brief.* type and the closed-verb law forbids inventing one build-side",
	"internal/modules/people:recordDedupeCandidate":            "a dedupe candidate is a QUESTION the system is asking about two records, not something that happened to either \u2014 the closed catalog (events.md \u00a75) defines no dedupe.* type, nothing downstream acts on a proposal, and an outbox row nobody consumes would be a kind invented to satisfy the rule rather than a reader. Audited because who proposed a merge, when, and on what evidence belongs on the record's own history rather than only in operator telemetry",
	// The finance mirror's seven write sites. One rationale covers all of them,
	// and each is keyed on its own function so an EIGHTH finance write arrives
	// unratified instead of inheriting a waiver somebody wrote about four
	// tables.
	//
	// The event catalog is CLOSED: an event type exists because the contract
	// declares one, and a build may not mint a type to satisfy this rule. The
	// catalog carries no finance verb at all, and neither adjacent type fits.
	// `mirror.*` is the overlay write-back stream, so staging an accounting fact
	// under it would route the envelope to subscribers watching for something
	// else. `organization.updated` would tell every subscriber that a company
	// record changed when none did — the same argument that already makes
	// people:WriteProviderClaims audit-only. A wrong envelope is acted on; an
	// absent one is not.
	//
	// The audit row is the half that could not wait, because it cannot be
	// written afterwards: an invoice mirrored without one stays permanently
	// unaccounted for, and the erasure and retention reasoning that reads
	// audit_log is blind to it.
	//
	// Audit-only here is SETTLED rather than pending. No finance verb exists in
	// the closed catalog, no consumer asks for one, and emitting would mean
	// minting public contract surface speculatively — which is the layering
	// working rather than a shortcut taken under it. It reads like the
	// attachment entries above and is their opposite: those skip a type that
	// could legitimately be declared, this has no type to skip.
	//
	// Said plainly because an exemption marked "waiting on a decision" is how a
	// temporary state becomes permanent with nobody choosing it. The condition
	// that reopens this one, so the silence has an expiry: a consumer that needs
	// to learn an invoice arrived. Then the contract declares the type FIRST —
	// the order a closed catalog requires — and these seven entries become emits
	// at the same call sites.
	"internal/modules/finance:insertInvoice":             "the mirror takes in an invoice \u2014 see the note above these seven entries",
	"internal/modules/finance:updateInvoice":             "the source restated an invoice \u2014 same ground",
	"internal/modules/finance:insertPayment":             "the mirror takes in a received payment \u2014 same ground",
	"internal/modules/finance:updatePayment":             "the source restated a payment \u2014 same ground",
	"internal/modules/finance:mirrorCustomer":            "the mirror takes in a directory entry \u2014 same ground, and this row carries no money at all: it records which name in the accounting source a link points at",
	"internal/modules/finance:updateExternalCustomer":    "the source renamed a directory entry \u2014 same ground",
	"internal/modules/finance:auditConnectionTransition": "the accounting source went down or came back \u2014 same ground. This one is a STATE change rather than a record fact, so even a ratified finance catalog would want a connection verb rather than an invoice one",
	// WriteFiltered no longer belongs here: the bulk export is a non-entity
	// operational event, so it moved from storekit.Audit to storekit.LogSystem
	// (system_log, 0074) \u2014 it writes no audit_log row at all now.
})

func TestEveryAuditedMutationEmitsAnEvent(t *testing.T) {
	t.Parallel()
	defer auditOnlyWrites.AssertAllMatched(t)
	emissionPathsByDir := map[string]map[string]bool{}
	fset := token.NewFileSet()
	for _, root := range []string{"internal/modules", "internal/compose", settingsStoreDir} {
		err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
			if err != nil || d.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") ||
				isIntegrationTagged(path) {
				return err
			}
			path = filepath.ToSlash(path)
			file, err := parser.ParseFile(fset, path, nil, 0)
			if err != nil {
				return err
			}
			dir := filepath.Dir(path)
			emissionPaths, ok := emissionPathsByDir[dir]
			if !ok {
				emissionPaths, err = emissionBearingFunctions(fset, dir)
				if err != nil {
					return err
				}
				emissionPathsByDir[dir] = emissionPaths
			}
			for _, decl := range file.Decls {
				fn, ok := decl.(*ast.FuncDecl)
				if !ok || fn.Body == nil {
					continue
				}
				var audits, emits bool
				ast.Inspect(fn.Body, func(n ast.Node) bool {
					switch node := n.(type) {
					case *ast.SelectorExpr:
						if pkg, ok := node.X.(*ast.Ident); ok && pkg.Name == "storekit" {
							switch node.Sel.Name {
							case "Audit", "AuditWithEvidence", "AuditWithTrail", "AuditEvent", "AuditEventWithEvidence":
								audits = true
							case "Emit", "EmitEvent", "EmitEventForEntity", "EmitPipeline", "EmitPipelinePayload":
								emits = true
							}
						}
					case *ast.CallExpr:
						if callee, ok := node.Fun.(*ast.Ident); ok && emissionPaths[callee.Name] {
							emits = true
						}
					}
					return true
				})
				if audits && !emits {
					key := filepath.ToSlash(filepath.Dir(path)) + ":" + fn.Name.Name
					if auditOnlyWrites.Waived(t, key) {
						continue
					}
					t.Errorf("%s: %s calls storekit.Audit without storekit.Emit — every audited mutation ships its event, or the exception is ratified in auditOnlyWrites",
						path, fn.Name.Name)
				}
			}
			return nil
		})
		if err != nil {
			t.Fatal(err)
		}
	}
}

// emissionBearingFunctions follows package-local plain-function calls so the
// gate accepts one named event-envelope helper without forcing every caller to
// spell Emit. Method helpers deliberately do not qualify: a receiver abstraction
// would make the transactional write shape too hard to verify statically here.
func emissionBearingFunctions(fset *token.FileSet, dir string) (map[string]bool, error) {
	emits := map[string]bool{}
	calls := map[string][]string{}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	for _, entry := range entries {
		path := filepath.Join(dir, entry.Name())
		if entry.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") || isIntegrationTagged(path) {
			continue
		}
		file, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return nil, err
		}
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Body == nil || fn.Recv != nil {
				continue
			}
			ast.Inspect(fn.Body, func(n ast.Node) bool {
				switch node := n.(type) {
				case *ast.SelectorExpr:
					if pkg, ok := node.X.(*ast.Ident); ok && pkg.Name == "storekit" {
						switch node.Sel.Name {
						case "Emit", "EmitEvent", "EmitEventForEntity", "EmitPipeline", "EmitPipelinePayload":
							emits[fn.Name.Name] = true
						}
					}
				case *ast.CallExpr:
					if callee, ok := node.Fun.(*ast.Ident); ok {
						calls[fn.Name.Name] = append(calls[fn.Name.Name], callee.Name)
					}
				}
				return true
			})
		}
	}
	for changed := true; changed; {
		changed = false
		for caller, callees := range calls {
			if emits[caller] {
				continue
			}
			for _, callee := range callees {
				if emits[callee] {
					emits[caller] = true
					changed = true
					break
				}
			}
		}
	}
	return emits, nil
}
